services:
  - type: web
    name: mflix-app
    env: node
    buildCommand: |
      npm install
      cd client && npm install && npm run build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false 