services:
  - type: web
    name: mflix-app
    env: node
    buildCommand: |
      echo "Installing server dependencies..."
      npm install
      echo "Installing client dependencies..."
      cd client
      npm install
      echo "Building client..."
      npm run build
      echo "Build completed. Contents of build directory:"
      ls -la build
      cd ..
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: CI
        value: false
    healthCheckPath: / 