services:
  - type: web
    name: mflix-app
    env: node
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false 